version: "3.8"

services:
  ddd-bank:
    networks:
      - new
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mysql
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    command: --log-bin-trust-function-creators=1
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      new:
        aliases:
          - database

  migrate:
    image: migrate/migrate
    volumes:
      - /home/zelshimy/Desktop/fun/DDD-bank/pkg/migrations:/migrations
    command:
      [
        "-path",
        "./migrations",
        "-database",
        "mysql://ziadshimy7:example-password@tcp(mysql)/users_db?charset=utf8",
        "up",
      ]
    networks:
      - new
    restart: on-failure
    links:
      - mysql
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data:
networks:
  new:
